import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Header from "@/components/organisms/Header";
import {WindowContextProvider} from "@/context/WindowContext";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <WindowContextProvider>
                <body className={inter.className}>
                <Header/>
                {children}
                </body>
            </WindowContextProvider>
        </html>
    )
}
